// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXR0PmLnrDU3AjMr7lqzcAphyVFI4yX6Q',
    appId: '1:700975403679:web:13ed183785de61cbb448aa',
    messagingSenderId: '700975403679',
    projectId: 'aplikasiimk-d675c',
    authDomain: 'aplikasiimk-d675c.firebaseapp.com',
    databaseURL: 'https://aplikasiimk-d675c-default-rtdb.firebaseio.com',
    storageBucket: 'aplikasiimk-d675c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiYVYaEzFkRcl3EL7EGUd0C_IPUjZss_k',
    appId: '1:700975403679:android:ca71cb7bf5c97996b448aa',
    messagingSenderId: '700975403679',
    projectId: 'aplikasiimk-d675c',
    databaseURL: 'https://aplikasiimk-d675c-default-rtdb.firebaseio.com',
    storageBucket: 'aplikasiimk-d675c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR7ujJbWR6KTwNh3tksXU6ZfnVJNi4WII',
    appId: '1:700975403679:ios:809a198b6c0b8449b448aa',
    messagingSenderId: '700975403679',
    projectId: 'aplikasiimk-d675c',
    databaseURL: 'https://aplikasiimk-d675c-default-rtdb.firebaseio.com',
    storageBucket: 'aplikasiimk-d675c.appspot.com',
    iosBundleId: 'com.example.aplikasispeechtotext',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR7ujJbWR6KTwNh3tksXU6ZfnVJNi4WII',
    appId: '1:700975403679:ios:5c15d824fdef7c69b448aa',
    messagingSenderId: '700975403679',
    projectId: 'aplikasiimk-d675c',
    databaseURL: 'https://aplikasiimk-d675c-default-rtdb.firebaseio.com',
    storageBucket: 'aplikasiimk-d675c.appspot.com',
    iosBundleId: 'com.example.aplikasispeechtotext.RunnerTests',
  );
}
